--- 
name: Linux
on: [push]    # Compact Flow Style Sequence
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo hello
steps:
# Plugin provided by GitHub to checkout the code
- uses: actions/checkout@v2
# Run multiple commands
- name: Run Tests
  run: "./configure\nmake\nmake test\n"